title: OWASP Secure Headers Project
description: Provides technical information about HTTP security headers.
baseurl: /www-project-secure-headers

remote_theme: just-the-docs/just-the-docs
url: https://righettod.github.io

permalink: /:title/

defaults:
  - scope:
      path: "mainsite"
    values:
      layout: "default"

include:
  - mainsite/

exclude:
  - subprojects/
  - archives/
  - ci/
  - logo/

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache