title: OWASP Secure Headers Project
description: Provides technical information about HTTP security headers.
baseurl: /www-project-secure-headers

theme: jekyll-theme-dinky

permalink: /:title/

defaults:
  - scope:
      path: "mainsite"
    values:
      layout: "default"

include:
  - mainsite/

exclude:
  - subprojects/
  - archives/
  - ci/
  - logo/

plugins:
  - jekyll-include-cache