name: New issue
description: Used to create new issue about the OSHP content.
title: "[ISSUE SUMMARY]"
labels: ["bug"]
body:
  - type: textarea
    id: issue_description
    attributes:
      label: Description
      description: Please provide a summary of the issue.
      placeholder: Typo in the header HSTS...
    validations:
      required: true
  - type: textarea
    id: issue_resources
    attributes:
      label: Additional resources
      description: Please provide, when possible/applicable, useful resources helping to handle the issue.
      placeholder: https://mydocumentation.com/article-on-problem.
    validations:
      required: false
