name: perform_monitoring_oshp_site_references
on:
  workflow_dispatch:
  push:
    paths:
    - 'tab_casestudies.md'
  schedule:
    - cron: '0 0 * * 0'
permissions: read-all     
jobs:
  build:
    runs-on: ubuntu-latest   
    steps:
    - uses: actions/checkout@v5
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run the validation
      run: |
        cd ci; python monitoring_oshp_site_references.py


