name: update_tab_stats_related_files
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 3 * *'  
  push:
    paths:
      - 'ci/tab_stats_generate_md_file.py'     
      - 'ci/tab_stats_generate_png_files.sh'     
      - 'ci/tab_stats_manage_generation.sh'         
jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        sudo apt install -y wget dos2unix sqlite3
    - name: Run update of the tab related files
      run: |
        cd ci; bash tab_stats_manage_generation.sh
    - name: Set up Git user
      run: git config --global user.email "gha@github.com"; git config --global user.name "GHActionBot"
    - name: Commit update
      run: git add --all; git commit -am "Sync tab stats related files"; git push
