name: Validate OWASP entity metadata

on:
  pull_request:
    paths:
      - '*.owasp.yaml'
  push:
    paths:
      - '*.owasp.yaml'

permissions:
  contents: read

concurrency:
  cancel-in-progress: true
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}

jobs:
  validate-metadata:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Validate metadata file
        uses: owasp/nest-schema/.github/actions/validate@2ce57bd63b3d0a2eed24017891d014c7b8bc15fd
